# Generated by Django 2.1.7 on 2019-04-09 08:15

from django.db import migrations, models
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190331_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='albumimage',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='albums'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='alt',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='albums'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=70),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='albums'),
        ),
    ]
