# Generated by Django 2.1.7 on 2019-04-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190409_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='tphoto',
            field=models.ImageField(blank=True, upload_to='albums'),
        ),
    ]
