# Generated by Django 2.1.7 on 2019-04-10 08:27

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_albumimage_tphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='tphoto',
        ),
        migrations.AlterField(
            model_name='album',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='tumbs'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='tumbs'),
        ),
    ]
